nasman/snapshots/urls.py
from django.conf.urls import patterns, url

from .views.filesystems import FileBrowser, FilesystemList
from .views import snapshots as snaps


urlpatterns = patterns(
    '',
    url(r'^file-browser$', FileBrowser.as_view(), name='file-browser'),
    url(r'^filesystems$', FilesystemList.as_view(), name='filesystems'),
    url(r'^snapshots$', snaps.SnapshotList.as_view(), name='snapshots'),
    url(r'^snapshots/refresh$', snaps.SnapshotList.as_view(refresh=True),
        name='snapshots-refresh'),
    url(r'^snapshot/add$', snaps.SnapshotCreate.as_view(), name='add-snap'),
    url(r'^snapshot/(?P<name>[\w\d@\-:.\/]+)/reindex$',
        snaps.SnapshotReindex.as_view(),
        name='reindex-snap'),
    url(r'^snapshot/(?P<name>[\w\d@\-:.\/]+)/mount$',
        snaps.SnapshotMount.as_view(),
        name='mount-snap'),
)

nasman/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^snapshots/', include('nasman.snapshots.urls',
                                namespace='snapshots')),
    url(r'^', include('nasman.core.urls', namespace='core'))
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wizfs/snapshots/urls.py
from django.conf.urls import patterns, url

from .views.base import DashboardView
from .views.filesystems import FileBrowser, FilesystemList, FilesystemDetail
from .views.filesystems import FilesystemCreate, FilesystemDelete
from .views.filesystems import FilesystemUpdate
from .views.snapshots import (SnapshotList,
                              SnapshotCreate,
                              SnapshotUpdate,
                              SnapshotDetail,
                              SnapshotDelete)


urlpatterns = patterns(
    '',
    url(r'^$', DashboardView.as_view(), name=u'dashboard'),
    url(r'^file-browser$', FileBrowser.as_view(), name=u'file-browser'),
    url(r'^filesystems$', FilesystemList.as_view(), name=u'filesystems'),
    url(r'^filesystem/(?P<pk>\d+)$', FilesystemDetail.as_view(),
        name=u'filesystem'),
    url(r'^filesystem/add$', FilesystemCreate.as_view(),
        name=u'add-fs'),
    url(r'^filesystem/(?P<pk>\d+)/delete$', FilesystemDelete.as_view(),
        name=u'delete-fs'),
    url(r'^filesystem/(?P<pk>\d+)/edit$', FilesystemUpdate.as_view(),
        name=u'edit-fs'),
    url(r'^snapshots$', SnapshotList.as_view(), name=u'snapshots'),
    url(r'^snapshot/(?P<pk>\d+)$', SnapshotDetail.as_view(),
        name=u'snapshot'),
    url(r'^snapshot/add$', SnapshotCreate.as_view(), name=u'add-snap'),
    url(r'^snapshot/(?P<pk>\d+)/edit$', SnapshotUpdate.as_view(),
        name=u'edit-snap'),
    url(r'^snapshot/(?P<pk>\d+)/delete$', SnapshotDelete.as_view(),
        name=u'delete-snap'),
)

wizfs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('wizfs.snapshots.urls', namespace='wizfs')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wizfs/snapshots/models.py
import os
from django.core.urlresolvers import reverse_lazy
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Filesystem(models.Model):
    """
    Model representing ZFS Filesystem
    """
    name = models.CharField(u'name', max_length=255, unique=True)
    parent = models.ForeignKey(
        u'self',
        related_name=u'children',
        null=True,
        blank=True
    )
    mountpoint = models.CharField(u'mountpoint', max_length=255, blank=True)

    class Meta:
        app_label = 'snapshots'

    def save(self, **kwargs):
        self.mountpoint = os.path.normpath(self.mountpoint)
        super(Filesystem, self).save(**kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('wizfs:filesystem', kwargs={'pk': self.pk})


@python_2_unicode_compatible
class Snapshot(models.Model):
    """
    Model representing a ZFS snapshot
    """
    name = models.CharField(u'name', max_length=255, unique=True)
    timestamp = models.DateTimeField(
        u'timestamp',
        null=True,
        auto_now_add=True
    )
    filesystem = models.ForeignKey(u'Filesystem', related_name=u'snapshots')

    class Meta:
        app_label = 'snapshots'

    def __str__(self):
        return self.name

    @property
    def base_name(self):
        """
        The base name of the snapshot, less the parent filesystem name
        """
        return u'%s' % self.name.split(u'@')[1]

    @property
    def parent_name(self):
        """
        The parent filesystem name of the snapshot
        """
        return u'%s' % self.name.split(u'@')[0]

    @property
    def mountpoint(self):
        return os.path.join(
            self.filesystem.mountpoint,
            self.base_name
        )


@python_2_unicode_compatible
class File(models.Model):
    """
    Model representing a file/directory/etc on the filesystem
    """
    full_path = models.TextField(u'full path')
    dirname = models.TextField(
        u'dirname',
        db_index=True
    )
    name = models.TextField(u'name')
    snapshot = models.ForeignKey(
        Snapshot,
        verbose_name=u'snapshot',
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    directory = models.BooleanField(default=False)
    mime_type = models.ForeignKey(
        u'IconMapping',
        verbose_name=u'mime-type',
        on_delete=models.SET_NULL,
        null=True
    )
    magic = models.CharField(u'magic', blank=True, max_length=255)
    modified = models.DateTimeField(u'modified')
    size = models.IntegerField(u'size', blank=True, null=True)

    class Meta:
        app_label = 'snapshots'

    def save(self, **kwargs):
        self.full_path = os.path.normpath(self.full_path)
        self.dirname = os.path.normpath(self.dirname)
        super(File, self).save(**kwargs)

    def __str__(self):
        return self.full_path

    @property
    def extension(self):
        """
        The file extension of this file
        :rtype: str
        """
        _, extension = os.path.splitext(self.full_path)
        return extension


@python_2_unicode_compatible
class IconMapping(models.Model):
    """
    Model to manage icon mapping to mimetypes
    """
    ICON_CHOICES = (
        ('fa-file-o', 'default'),
        ('fa-file-archive-o', 'archive'),
        ('fa-file-audio-o', 'audio'),
        ('fa-file-code-o', 'code'),
        ('fa-file-excel-o', 'excel'),
        ('fa-file-image-o', 'image'),
        ('fa-file-pdf-o', 'pdf'),
        ('fa-file-powerpoint-o', 'powerpoint'),
        ('fa-file-text-o', 'text'),
        ('fa-file-video-o', 'video'),
        ('fa-file-word-o', 'word'),
        ('fa-folder-open-o', 'directory')
    )
    icon = models.CharField(
        u'icon',
        max_length=25,
        choices=ICON_CHOICES,
        default='fa-file-o'
    )
    mime_type = models.CharField(
        u'mime-type',
        max_length=255,
        primary_key=True,
        db_index=True
    )

    class Meta:
        app_label = 'snapshots'

    def save(self, **kwargs):
        icon_mapping = {x[1]: x[0] for x in self.ICON_CHOICES}
        if self.icon == 'fa-file-o':
            major = self.mime_type.split('/')[0]
            if major in icon_mapping:
                self.icon = icon_mapping[major]
        super(IconMapping, self).save(**kwargs)

    def __str__(self):
        return self.mime_type

wizfs/snapshots/forms.py
from django import forms

from .models import Filesystem, Snapshot


class FilesystemForm(forms.ModelForm):

    class Meta:
        model = Filesystem
        fields = [u'name', u'mountpoint', u'parent']


class SnapshotForm(forms.ModelForm):

    class Meta:
        model = Snapshot
        fields = [u'name', u'filesystem']

nasman/snapshots/views/filesystems.py
from collections import defaultdict
from datetime import datetime
import logging
from pathlib import Path
from braces.views import SetHeadlineMixin

from django.core.urlresolvers import reverse_lazy
import magic
from vanilla import TemplateView, FormView

from ..models import IconMapping
from ..forms import FileBrowserForm
from ..utils.zfs import ZFSUtil

logger = logging.getLogger(__name__)


class FileBrowser(FormView, SetHeadlineMixin):
    """
    Browse live filesystem using python os stdlib
    """
    template_name = 'file_list.html'
    headline = 'File Browser'
    form_class = FileBrowserForm
    success_url = reverse_lazy('nasman:file-browser')

    def get_context_data(self, **kwargs):
        """
        Build the context data for the file browser
        """
        context = super(FileBrowser, self).get_context_data(**kwargs)
        form = context['form']
        filesystem = None
        snapshot = None
        if form.is_bound:
            form.is_valid()
            filesystem = form.cleaned_data.get('filesystem')
            snapshot = form.cleaned_data.get('snapshot')
        if 'path' in form.changed_data:
            path = form.cleaned_data['path']
        elif 'filesystem' in form.changed_data:
            filesystem.mount()
            path = Path(filesystem.mountpoint)
        elif 'snapshot' in form.changed_data:
            snapshot.mount()
            path = Path(snapshot.mountpoint)
        else:
            path = Path('/')
        root = path.root
        icon_mapping = defaultdict(
            lambda: 'fa-file-o',
            {x.mime_type: x.icon
             for x in IconMapping.objects.all()})

        # The file list/browser
        object_list = []
        for x in path.iterdir():
            try:
                mime_type = magic.from_file(str(x), mime=True).decode('utf8')
            except OSError as e:
                logger.warn('Unable to get mime_type of %s', str(x))
                mime_type = None
            object_list.append({
                'name': x.name,
                'full_path': x,
                'directory': x.is_dir(),
                'mime_type': mime_type,
                'modified': datetime.fromtimestamp(x.lstat().st_mtime),
                'size': x.lstat().st_size,
                'icon': icon_mapping[mime_type],
            })
        object_list.sort(key=lambda k: (not k['directory'], k['name']))

        # Path breadcrumbs
        breadcrumbs = sorted(path.parents) + [path]

        # The up one '..' link
        up_one = None
        if path != root:
            up_one = path.parent

        # TODO: context relevant snapshot list
        context.update({
            'up_one': up_one,
            'files_list': object_list,
            'path': breadcrumbs,
            'browser_title': breadcrumbs[-1],
        })
        return context

    def form_valid(self, form):
        return self.form_invalid(form)


class FilesystemList(TemplateView, SetHeadlineMixin):
    template_name = 'filesystem_list.html'
    headline = 'ZFS Filesystems'

    def get_context_data(self, **kwargs):
        context = super(FilesystemList, self).get_context_data()
        context['object_list'] = ZFSUtil.get_filesystems()
        return context

nasman/snapshots/views/snapshots.py
import logging
from subprocess import CalledProcessError

from braces.views import MessageMixin, JSONResponseMixin, AjaxResponseMixin, \
    SetHeadlineMixin
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.views.generic import View
from vanilla import FormView, ListView

from ..forms import SnapshotForm
from .. import tasks
from ..models import ZFSSnapshot
from ..utils.zfs import ZFSUtil

logger = logging.getLogger(__name__)


class SnapshotCreate(MessageMixin, FormView, SetHeadlineMixin):
    headline = 'Create new snapshot'
    form_class = SnapshotForm
    template_name = 'snapshot_form.html'
    success_url = reverse_lazy('nasman:snapshots')

    def form_valid(self, form):
        snap_name = form.cleaned_data['name']
        fs_name = form.cleaned_data['filesystem']
        recurse = form.cleaned_data['recursive']
        try:
            ZFSUtil.create_snapshot(snap_name, fs_name, recurse)
        except CalledProcessError as e:
            self.messages.error(
                '{1}'.format(
                    snap_name,
                    str(e.output.decode('utf-8'))
                ).capitalize(),
                extra_tags='ban'
            )
        else:
            self.messages.info(
                'Created {0}'.format(form.cleaned_data['name'])
            )
        return super(SnapshotCreate, self).form_valid(form)


class SnapshotList(JSONResponseMixin, AjaxResponseMixin, ListView,
                   SetHeadlineMixin):
    headline = 'ZFS Snapshots'
    template_name = 'snapshot_list.html'
    refresh = False
    context_object_name = 'snapshot_list'

    def get_ajax(self, request, *args, **kwargs):
        draw = int(self.request.GET.get('draw', 0)) + 1
        start = int(self.request.GET.get('start', 0))
        end = start + int(self.request.GET.get('length', 1))
        records = [
            {'name': x.name,
             'created': naturaltime(x.timestamp),
             }
            for x in self.get_queryset()
            ]
        record_count = len(records)
        json_dict = {
            'draw': draw,
            'recordsTotal': record_count,
            'recordsFiltered': record_count,
            'data': records[start:end]
        }
        return self.render_json_response(json_dict)

    def get_queryset(self):
        if self.refresh:
            ZFSSnapshot.objects.refresh_from_os()
        return ZFSSnapshot.objects.all()


class SnapshotReindex(MessageMixin, View):
    http_method_names = ['get']

    def get(self, request, name=None):
        res = tasks.index_snapshot.apply_async(args=(name, ))
        self.messages.info('Reindex of {0} started'.format(name))
        return redirect('nasman:dashboard')


class SnapshotMount(MessageMixin, View):
    http_method_names = ['get']

    def get(self, request, name=None):
        snap = ZFSUtil.get_snapshot(name)
        if snap.is_mounted:
            if snap.unmount():
                self.messages.info('{0} is now unmounted'.format(name))
            else:
                self.messages.error('Failed to unmount {0}'.format(name))
        else:
            if snap.mount():
                self.messages.info('{0} is now mounted at {1}'.format(
                    name, snap.mountpoint))
        return redirect('nasman:snapshots')

wizfs/snapshots/views/base.py
from braces.views import JSONResponseMixin, AjaxResponseMixin, SetHeadlineMixin
from vanilla import TemplateView


class BaseView(SetHeadlineMixin):
    pass


class DashboardView(JSONResponseMixin,
                    AjaxResponseMixin,
                    BaseView,
                    TemplateView):
    """
    View for the homepage
    """
    http_method_names = [u'get']
    template_name = u'dashboard.html'
    headline = u'WiZFS Dashboard'

wizfs/snapshots/views/snapshots.py
from braces.views import MessageMixin, JSONResponseMixin, AjaxResponseMixin
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from vanilla import (CreateView,
                     ListView,
                     UpdateView,
                     DetailView,
                     DeleteView)

from ..forms import SnapshotForm
from ..models import Snapshot
from ..utils import ZFSHelper
from .base import BaseView


class SnapshotCreate(MessageMixin, BaseView, CreateView):
    model = Snapshot
    headline = u'Add New Filesystem'
    form_class = SnapshotForm

    def get(self, request, *args, **kwargs):
        """
        If "auto" query parameter is passed then use utility to add all found
        filesystems
        """
        if request.GET.get(u'auto'):
            util = ZFSHelper()
            util.create_snapshot_objects()
            self.messages.info(u'Added all snapshots automatically')
            return redirect(u'wizfs:snapshots')
        return super(SnapshotCreate, self).get(request, *args, **kwargs)


class SnapshotList(JSONResponseMixin, AjaxResponseMixin, BaseView, ListView):
    model = Snapshot
    headline = u'ZFS Snapshots'


class SnapshotUpdate(BaseView, UpdateView):
    model = Snapshot
    success_url = reverse_lazy(u'wizfs:snapshots')
    form_class = SnapshotForm

    def get_headline(self):
        return u'Edit %s snapshot' % self.get_object().name


class SnapshotDetail(JSONResponseMixin,
                     AjaxResponseMixin,
                     MessageMixin,
                     BaseView,
                     DetailView):
    model = Snapshot

    def get_headline(self):
        return u'Snapshot %s Details' % self.get_object().name


class SnapshotDelete(BaseView, DeleteView):
    model = Snapshot
    success_url = reverse_lazy(u'wizfs:snapshots')

    def get_headline(self):
        return u'Delete snapshot: %s ?' % self.get_object().name

nasman/snapshots/templates/dashboard.html
{% extends "base.html" %}
{% load static i18n humanize %}
{% block content %}
  <div class="row">
    <!-- Snapshot list -->
    <div class="col-md-6">
      <div class="box box-primary snapshot-box">
        <div class="box-header with-border">
          <h3 class="box-title"><i class="fa fa-camera"></i> Snapshots</h3>

          <div class="box-tools pull-right">
            <div class="btn-group">
              <button href="{% url "nasman:snapshots-refresh" %}#content"
                      class="btn btn-primary btn-sm snap-refresh">
                <i class="fa fa-refresh"></i>
              </button>
              <a href="{% url "nasman:add-snap" %}"
                 class="btn btn-success btn-sm">
                <i class="fa fa-plus"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="box-body table">
          <table
              id="snapshot-list"
              class="table table-striped table-hover">
            <thead>
            <tr>
              <th>Name</th>
              <th>Created</th>
              <th style="text-align: right">Actions</th>
            </tr>
            </thead>
          </table>
        </div>
      </div>
    </div>
    <!-- /Snapshot list -->

    <!-- Filesystem list -->
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title"><i class="fa fa-database"></i> Filesystems</h3>

          <div class="box-tools pull-right">
            <div class="btn-group">
              <a href="#"
                 class="btn btn-success btn-sm">
                <i class="fa fa-plus"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="box-body table-responsive no-padding">
          <table class="table table-striped table-hover">
            <thead>
            <tr>
              <th>Name</th>
              <th>Mountpoint</th>
            </tr>
            </thead>
            <tbody>
            {% for fs in object_list %}
              <tr>
                <td>{{ fs.name }}</td>
                <td>{{ fs.mountpoint }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- /Filesystem list -->
  </div>
{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script type="text/javascript">
    var snapshot_list;
    var snapshot_box = $('div.snapshot-box');
    function actionButtons(data, type, row, meta) {
      var reindex_url = '/snapshot/' + row.name + '/reindex';
      var mount_url = '/snapshot/' + row.name + '/mount';
      return '<div class="btn-group pull-right">' +
          '<button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">' +
          '<i class="fa fa-cog"></i></button>' +
          '<ul class="dropdown-menu">' +
          '<li><a href="' + reindex_url + '">Reindex</a></li>' +
          '<li><a href="' + mount_url + '">Mount</a></li></ul></div>';
    }
    $(document).ready(function () {
      $('button.snap-refresh').click(function () {
        $.get(
            '/snapshots/refresh',
            function () {
              snapshot_list.api().ajax.reload();
            }
        );
      });
      snapshot_list = $('#snapshot-list').dataTable({
        'lengthChange': false,
        'searching': false,
        'serverSide': true,
        'ajax': '{% url "nasman:snapshots" %}',
        'ordering': false,
        'pageLength': 5,
        'columnDefs': [
          {
            'targets': -1,
            'render': actionButtons,
            'sortable': false
          },
          {
            'targets': 0,
            'data': 'name'
          },
          {
            'targets': 1,
            'data': 'created',
            'orderData': 2
          }
        ]
      });
      snapshot_list.on('preXhr.dt', function (e, settings, data) {
        snapshot_box.append('<div class="overlay snapshot-overlay"><i class="fa fa-refresh fa-spin"></i></div>');
      });
      snapshot_list.on('xhr.dt', function (e, settings, data) {
        snapshot_box.find('div.snapshot-overlay').remove();
      })
    });
  </script>
{% endblock javascript %}

nasman/snapshots/templates/file_list.html
{% load staticfiles i18n humanize %}
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="col-lg-10">
    <h2>File Browser</h2>
    <ol class="breadcrumb">
      {% for directory in path %}
        {% if forloop.first %}
          <li{% if foorloop.last %} class="active"{% endif %}>
            <a class="breadcrumb-link" data-target="{{ directory }}"><i
                    class="fa fa-folder"></i></a>
          </li>
        {% else %}
          <li{% if forloop.last %} class="active"{% endif %}>
            {% if not forloop.last %}
              <a class="breadcrumb-link" data-target="{{ directory }}">
            {% endif %}
            {{ directory.name }}
            {% if not forloop.last %}
              </a>
            {% endif %}
          </li>
        {% endif %}
      {% endfor %}
    </ol>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Custom responsive table </h5>

          <div ibox-tools></div>
        </div>
        <div class="ibox-content">
          <div class="row">
            <div class="col-sm-5 m-b-xs"><select
                    class="input-sm form-control input-s-sm inline">
              <option value="0">Option 1</option>
              <option value="1">Option 2</option>
              <option value="2">Option 3</option>
              <option value="3">Option 4</option>
            </select>
            </div>
            <div class="col-sm-4 m-b-xs">
              <div data-toggle="buttons" class="btn-group">
                <label class="btn btn-sm btn-white"> <input type="radio"
                                                            id="option1"
                                                            name="options"> Day
                </label>
                <label class="btn btn-sm btn-white active"> <input type="radio"
                                                                   id="option2"
                                                                   name="options">
                  Week </label>
                <label class="btn btn-sm btn-white"> <input type="radio"
                                                            id="option3"
                                                            name="options">
                  Month </label>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="input-group"><input type="text" placeholder="Search"
                                              class="input-sm form-control"> <span
                      class="input-group-btn">
                                        <button type="button"
                                                class="btn btn-sm btn-primary">
                                          Go!
                                        </button> </span></div>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
              <tr>

                <th></th>
                <th>Project</th>
                <th>Completed</th>
                <th>Task</th>
                <th>Date</th>
                <th>Action</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td><input icheck type="checkbox" ng-model="main.checkOne">
                </td>
                <td>Project
                  <small>This is example of project</small>
                </td>
                <td>
                  <pie-chart data="main.PieChart4.data"
                             options="main.PieChart4.options"></pie-chart>
                </td>
                <td>20%</td>
                <td>Jul 14, 2013</td>
                <td><a href=""><i class="fa fa-check text-navy"></i></a></td>
              </tr>
              <tr>
                <td><input icheck type="checkbox" ng-model="main.unCheck1">
                </td>
                <td>Alpha project</td>
                <td>
                  <pie-chart data="main.PieChart3.data"
                             options="main.PieChart3.options"></pie-chart>
                </td>
                <td>40%</td>
                <td>Jul 16, 2013</td>
                <td><a href=""><i class="fa fa-check text-navy"></i></a></td>
              </tr>
              <tr>
                <td><input icheck type="checkbox" ng-model="main.unCheck2">
                </td>
                <td>Betha project</td>
                <td>
                  <pie-chart data="main.PieChart2.data"
                             options="main.PieChart2.options"></pie-chart>
                </td>
                <td>75%</td>
                <td>Jul 18, 2013</td>
                <td><a href=""><i class="fa fa-check text-navy"></i></a></td>
              </tr>
              <tr>
                <td><input icheck type="checkbox" ng-model="main.unCheck3">
                </td>
                <td>Gamma project</td>
                <td>
                  <pie-chart data="main.PieChart5.data"
                             options="main.PieChart5.options"></pie-chart>
                </td>
                <td>18%</td>
                <td>Jul 22, 2013</td>
                <td><a href=""><i class="fa fa-check text-navy"></i></a></td>
              </tr>
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>

  </div>
</div>

nasman/snapshots/templates/file_list_js.html
<script type="application/javascript">
  $('select#id_filesystem').change(function ()
  {
    $('#id_path').val('');
    $('#id_snapshot').val('');
    $('#filebrowser-form').submit();
  });

  $('.file-link, .breadcrumb-link').each(function () {
    $(this).click(function() {
      $('select#id_filesystem').val('None');
      $('#id_snapshot').val('');
      $('#id_path').val($(this).attr('data-target'));
      $('#filebrowser-form').submit();
    });
  });
  
  $('#snapshot-list').find('li a').each(function () {
    $(this).click(function () {
      $('#id_path').val('');
      $('select#id_filesystem').val('None');
      $('#id_snapshot').val($(this).attr('data-target'));
      $('#filebrowser-form').submit();
    })
  })
</script>

nasman/snapshots/templates/filesystem_list.html
{% extends "base.html" %}
{% load staticfiles i18n %}

{% block content %}
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title"><i class="fa fa-database"></i> Filesystems</h3>

    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-striped table-hover">
        <thead>
        <tr>
          <th>Name</th>
          <th>Mountpoint</th>
        </tr>
        </thead>
        <tbody>
        {% for fs in object_list %}
          <tr>
            <td>{{ fs.name }}</td>
            <td>{{ fs.mountpoint }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}

nasman/snapshots/templates/snapshot_form.html
{% extends "base_form.html" %}
{% load floppyforms staticfiles i18n %}

{% block form_block %}
  {% form form using %}
      {% csrf_token %}
      {% formrow form.name form.filesystem using "floppyforms/rows/bootstrap.html" %}
      {% formrow form.recursive using "floppyforms/rows/checkbox_row.html" %}
  {% endform %}
{% endblock form_block %}

nasman/snapshots/templates/snapshot_list.html
{% extends "base.html" %}
{% load static i18n humanize bootstrap_pagination %}

{% block content %}
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title"><i class="fa fa-camera"></i> Snapshots</h3>

      <div class="box-tools pull-right">
        <div class="btn-group">
          <a href="{% url "nasman:snapshots-refresh" %}#content"
             class="btn btn-primary btn-sm">
            <i class="fa fa-refresh"></i>
          </a>
          <a href="{% url "nasman:add-snap" %}"
             class="btn btn-success btn-sm">
            <i class="fa fa-plus"></i>
          </a>
        </div>
      </div>
    </div>
    <div class="box-body table-responsive no-padding">
      <table
          id="snapshot-list"
          class="table table-striped table-hover">
        <thead>
        <tr>
          <th>Name</th>
          <th>Created</th>
          <th style="text-align: right">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for snap in snapshot_list %}
          <tr>
            <td>{{ snap.name }}</td>
            <td>{{ snap.timestamp|naturaltime }}</td>
            <td>
              <div class="pull-right">
                <a class="btn btn-xs {% if snap.is_mounted %}btn-warning{% else %}btn-info{% endif %}"
                   href="{% url "nasman:mount-snap" name=snap.name %}">
                  {% if snap.is_mounted %}Unmount{% else %}Mount{% endif %}
                </a>
                <a class="btn btn-primary btn-xs"
                   href="{% url "nasman:reindex-snap" name=snap.name %}">Reindex</a>
                <a class="btn btn-danger btn-xs disabled"
                   href="#">Delete</a>
              </div>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script type="text/javascript">
    $('#snapshot-snapshot-list').dataTable({
      "bPaginate": true,
      "bLengthChange": false,
      "bFilter": false,
      "bSort": true,
      "bInfo": true,
      "bAutoWidth": false
    });
  </script>
{% endblock javascript %}